title: WildFly - JBoss Application Server has a new name... WildFly.
author: WildFly Development Team
description: WildFly, the project formerly known as JBossAS, is a Java Application Server


forum_url: https://community.jboss.org/en/wildfly?view=discussions
github_repo: https://github.com/jbossas/jboss-as
irc_url: irc://irc.freenode.net#jboss
#Needs confirmation
jira_key:  WILDFLY
jira_url: https://issues.jboss.org/browse/WILDFLY
redhat_url: http://community.redhat.com/
website_source_repo: http://github.com/jbossas/wildfly-site/settings/collaboration
wiki_url: https://community.jboss.org/en/wildfly


profiles:
  development:
    base_url: http://localhost:4242
    logo_base_url: https://www.jboss.org/dms/wildfly_splash
    minify: false
    google_plusone: true
    noindex: true

  sandbox:
    base_url: http://people.redhat.com/~rploski/rename
    logo_base_url: https://www.jboss.org/dms/wildfly_splash
    minify: false
    google_plusone: false
    noindex: true
    deploy:
      host: people.redhat.com
      path: /home/remote/rploski/public_html/rename
      uncommitted: true

  staging:
    base_url: http://localhost:4242
    logo_base_url: https://www.jboss.org/dms/wildfly_splash
    minify: false
    google_plusone: false
    noindex: true

  production:
    base_url: http://wildfly.org
    logo_base_url: https://www.jboss.org/dms/wildfly_splash
    minify: true
    google_plusone: false
    noindex: false
    google_analytics: UA-40221748-1


