title:  WildFly Application Server
author: JBoss Development Team
description: WildFly, the project formerly known as JBossAS, is a Java Application Server

#Needs confirmation
jira_key:  WILDFLY

profiles:
  development:
    base_url: http://localhost:4242
    minify: false
    google_plusone: false
    noindex: true
  sandbox:
    base_url: http://wildfly-jbossway.rhcloud.com

