title:  WildFly Application Server
author: JBoss Development Team
description: WildFly, the project formerly known as JBossAS, is a Java Application Server


forum_url: https://community.jboss.org/en/wildfly?view=discussions
github_repo: https://github.com/jbossas/jboss-as
irc_url: irc://irc.freenode.net#jboss
#Needs confirmation
jira_key:  WILDFLY
jira_url: https://issues.jboss.org/browse/WILDFLY
redhat_url: http://community.redhat.com/
website_source_repo: http://github.com/jbossas/wildfly-site/settings/collaboration
wiki_url: https://community.jboss.org/en/wildfly


profiles:
  development:
    base_url: http://localhost:4242
    minify: false
    google_plusone: false
    noindex: true
  sandbox:
    base_url: http://wildfly-jbossway.rhcloud.com

